---
baseURI: https://github.com/graphsense/graphsense-tagpacks
targetKeyspace: tagpacks
fields:
  header:
    - title
    - creator
    - description
    - tags
  tag:
    - address
    - label
    - source
    - currency
    - category
    - lastmod
categories:
  - Organization
  - Miner
  - Exchange
  - Walletprovider
  - Marketplace
  - Mixingservice