baseURI: https://github.com/graphsense/graphsense-tagpacks/blob/master
categories:
- Organization
- Ponzi Scheme
- Miner
- Mixing Service
- Hack
- Service/Other
- Ransomware
- Scam
- Marketplace
- Sextortion
- Wallet Service
- Exchange
- Gambling
fields:
  header:
  - title
  - creator
  - description
  - tags
  tag:
  - address
  - label
  - source
  - currency
  - category
  - lastmod
targetKeyspace: tagpacks
