baseURI: https://github.com/graphsense/graphsense-tagpacks/blob/master
categories:
- Exchange
- Wallet Service
- Service/Other
- Miner
- Marketplace
- Gambling
- Mixing Service
- Organization
- Scam
- Sextortion
- Hack
- Ransomware
- Ponzi Scheme
fields:
  header:
  - title
  - creator
  - description
  - tags
  tag:
  - address
  - label
  - source
  - currency
  - category
  - lastmod
targetKeyspace: tagpacks
