baseURI: https://github.com/graphsense/graphsense-tagpacks/blob/master
categories:
- Scam
- Sextortion
- Marketplace
- Mixing Service
- Wallet Service
- Hack
- Ransomware
- Ponzi Scheme
- Exchange
- Organization
- Gambling
- Miner
- Service/Other
fields:
  header:
  - title
  - creator
  - description
  - tags
  tag:
  - address
  - label
  - source
  - currency
  - category
  - lastmod
targetKeyspace: tagpacks
