categories:
- Exchange
- Wallet Service
- Miner
- Marketplace
- Gambling
- Mixing Service
- Other
- Unspecified
abuses:
- Scam
- Sextortion
- Hack
- Ransomware
- Ponzi Scheme
fields:
  header:
  - title
  - creator
  - description
  - tags
  tag:
  - address
  - label
  - source
  - currency
  - category
  - lastmod
  - abuse
